from src.api.schemas.domain import CandidateProfile


TALENT_INVENTORY = [
    CandidateProfile(
        engineer_id="eng-001",
        engineer_name="Jordan Lee",
        location="Detroit MI",
        seniority="senior",
        availability_status="available_now",
        rate_band=115,
        skills=["Python", "SQL", "Data Modeling", "ETL", "Stakeholder Communication"],
        technologies=["AWS", "Snowflake", "dbt", "Airflow", "PostgreSQL"],
        domains=["healthcare", "data_platform"],
        certifications=["AWS Solutions Architect"],
        recent_client_industries=["healthcare", "insurance"],
        last_profile_refresh_days=9,
        placement_success_rate=0.91,
    ),
    CandidateProfile(
        engineer_id="eng-002",
        engineer_name="Taylor Kim",
        location="Chicago IL",
        seniority="lead",
        availability_status="available_in_2_weeks",
        rate_band=132,
        skills=["Platform Engineering", "Terraform", "Kubernetes", "Incident Response", "Mentorship"],
        technologies=["AWS", "Terraform", "Kubernetes", "Datadog", "GitHub Actions"],
        domains=["fintech", "platform"],
        certifications=["CKA"],
        recent_client_industries=["financial_services"],
        last_profile_refresh_days=14,
        placement_success_rate=0.88,
    ),
    CandidateProfile(
        engineer_id="eng-003",
        engineer_name="Alex Romero",
        location="Remote",
        seniority="senior",
        availability_status="available_now",
        rate_band=124,
        skills=["Python", "SQL", "Machine Learning", "Forecasting", "Experimentation"],
        technologies=["GCP", "BigQuery", "Airflow", "Python", "Looker"],
        domains=["staffing", "marketplace", "analytics"],
        certifications=[],
        recent_client_industries=["staffing", "saas"],
        last_profile_refresh_days=5,
        placement_success_rate=0.84,
    ),
    CandidateProfile(
        engineer_id="eng-004",
        engineer_name="Morgan Patel",
        location="Detroit MI",
        seniority="senior",
        availability_status="available_in_30_days",
        rate_band=108,
        skills=["Python", "SQL", "Data Warehousing", "Business Analysis", "Client Delivery"],
        technologies=["Azure", "Synapse", "dbt", "Power BI", "PostgreSQL"],
        domains=["healthcare", "public_sector", "data_platform"],
        certifications=["Azure Data Engineer Associate"],
        recent_client_industries=["healthcare", "public_sector"],
        last_profile_refresh_days=22,
        placement_success_rate=0.79,
    ),
]
